platform :ios, '6.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'RNCryptor', '~> 2.2'
pod 'NJKWebViewProgress', '~> 0.2.3'
